services:
  fichart:
    image: jp8002/fichart
    ports:
      - "8000:8000"

    volumes:
      - ./fichart:/djangoapp

    # depends_on:
    #   - db

    environment:
      - "PIP_ROOT_USER_ACTION=ignore"
  
#   db:
#     image: postgres:18
#     volumes:
#       - postgres_data:/var/lib/postgresql/
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
#   postgres_data: