name: ğŸš€ Build and Deploy Django App - Fichart

on:
  push:
    branches:
      - deployment  # sÃ³ roda quando houver push na branch de deploy
  workflow_dispatch:  # permite execuÃ§Ã£o manual

jobs:
  build:
    name: ğŸ§© Build
    runs-on: ubuntu-latest

    permissions:
      contents: read  # necessÃ¡rio para o checkout

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 3.13 ainda Ã© experimental em algumas libs

      - name: ğŸ“¦ Instalar dependÃªncias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r fichart/requirements.txt

      - name: ğŸ“¦ Preparar artefato para deploy
        uses: actions/upload-artifact@v4
        with:
          name: fichart-app
          path: |
            .
            !venv/
            !**/__pycache__/
            !**/*.pyc
            !.git/
            !.github/
            !.vscode/
            !dotenv_files/
            !db.sqlite3

  deploy:
    name: ğŸš€ Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ğŸ“¦ Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: fichart-app

      - name: ğŸŒ Deploy no Azure
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Fichart'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1512A90C697E41C981BE77BD56FA1D03 }}
